name: Playwright Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Install Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: 20
          cache: 'npm'  # Built-in caching

      - name: Install dependencies
        run: npm ci  # More reliable than npm install for CI

      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps
          npx playwright install chromium
        env:
          PLAYWRIGHT_BROWSERS_PATH: ./browsers  # Custom path to avoid permission issues

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true  # Important for Playwright CI optimizations
          LOGIN_USER: ${{ secrets.LOGIN_USER }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}